# -*- coding: utf-8 -*-
"""pa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvSFPo--_BLazvU0AhhRUOy5oQtB2Osz
"""

# Input Num
idade = 25
print(idade)
altura = 1.75
nuumero_complexo = 2 + 3j

# text
nome = 'joao'

#bool
esta_chovendo = False

"""Algoritmo de calcula o quadrado

# Entrada
 Ler o Dado

# Processamento
 multiplica o lado pelo lado

# Saida
 Mostrar resultado
"""

# Entrada
lado = 6

# Processamento
quadrado = lado * lado

# Saida
print(f" total da area do quadrado: {quadrado}")

tamanho = float(input("Digite o tamanho da sala em metros: "))
comprimento = float(input("Digite o comprimento da sala em metros: "))
area = tamanho * comprimento
print(f"A área da sala é: {area} metros quadrados")

"""escrever um algoritmo que recebe 04 notas e calcula a media e exibe a media"""

# Media de 04 Notas
nome = input("Digite o nome do aluno: ")
n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
n3 = float(input("Digite a terceira nota: "))
n4 = float(input("Digite a quarta nota: "))
md = (n1 + n2 + n3 + n4 ) / 4
print(f'A media do aluno {nome} é: {md}')

# Dobro de Um Numero
num = float(input("Digite um numero: "))
dob = num * 2
print(f"O Dobro do numero selecionado é: {dob}")